server:
  port: 8080

spring:
  profiles:
    active: local  # 기본은 local 환경
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [traceId=%X{traceId}] [eventId=%X{eventId}] [userId=%X{userId}] [ip=%X{clientIp}] %-5level %logger{36} - %msg%n"

chat:
  redis:
    enabled: true

tribe:
  auth:
    enabled: true
