server:
  forward-headers-strategy: framework

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000
    verified-state-expiration-millis: 1800000
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_KEY:test-kakao-key}
            client-secret: ${KAKAO_CLIENT_SECRET:test-kakao-secret}
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      database: ${REDIS_DB:0}

management:
  server:
    port: 9090
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true
    prometheus:
      enabled: true

jwt:
  secret: ${PROD_JWT_SECRET}

app:
  mail:
    from-name: ${PROD_MAIL_FROM_NAME:Tribe}
  url: ${APP_URL:http://localhost:3000}
  auth:
    cookie:
      secure: true
      same-site: None

google:
  maps:
    key: ${GOOGLE_KEY}

gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: ${GEMINI_API_URL:https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent}

exchange:
  rate:
    api-url: ${EXCHANGE_RATE_API_URL:https://oapi.koreaexim.go.kr}
    key: ${EXCHANGE_RATE_API_KEY}

cloudinary:
  url: ${CLOUDINARY_URL}

discord:
  webhook-url: ${DISCORD_WEBHOOK_URL:}

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
