apiVersion: v1
kind: ConfigMap
metadata:
  name: tribe-api-config
data:
  REDIS_HOST: "shared-redis-master.cache.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  APP_URL: "https://tribe.jaehyuns.com"
  PROD_MAIL_FROM_NAME: "Tribe"
  DISCORD_WEBHOOK_URL: ""
