apiVersion: ENC[AES256_GCM,data:LQw=,iv:JrQnUmafTYw+vO9m9Dv4MvUqpBlrDnCiwDE+taXKk5w=,tag:iHzv1G/GDQ5IIMDHrR60Iw==,type:str]
kind: ENC[AES256_GCM,data:azvE+bgxfpl0,iv:tRjAbCCD1u0xpGOgDZt0wspq5FBe1byAHSNR2DvlJGI=,tag:RY6FS3z0RAOuNw46hIs1HQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:hdfYUHTRVyaqLNWCqKv9Tw==,iv:dFPZQiz9+QCgXcx5DZKdmuWTcQFIfGnZIFzfhd4Iipo=,tag:yeYVdYm+UpCR0BIbbdngBA==,type:str]
data:
    REDIS_HOST: ENC[AES256_GCM,data:w/EfmBbsNmbxWW4c7MFd5GP0XKD4fNmxPoxx+wN2w6BxWavtiK62Nz23/A==,iv:hvRNJ4JnwRVxcqUphvRyjLF6BKEmXr5+TU+sTR7dsS8=,tag:FUVB8NG2HL9155f9nAvG1w==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:BL2t7Q==,iv:hhKYuQv4VbaPues0/+zkHLB0H27t1eAH4FQS6hWul08=,tag://vjSyuBodsqsDiYZtv//w==,type:str]
    REDIS_DB: ENC[AES256_GCM,data:Cg==,iv:dzs04ay9gT4KJ9AL55N3Tx+aveDEGCRmKXhoErjD7Jw=,tag:6zzFcIUKUCnLZetlvkkuKw==,type:str]
    APP_URL: ENC[AES256_GCM,data:gmjqrf1LxuqKcPweE76a5Hep,iv:bSWykPYQnEXgH44ylhYZsRA/1esTBVfeEeSFh6KSb3Q=,tag:FdEET7i11FBifI3BeQLjJQ==,type:str]
    PROD_MAIL_FROM_NAME: ENC[AES256_GCM,data:8D9O7j4=,iv:Y/FQkDFbD/9lmVjcRzVLcmMvi+Ad4D7BKQ5eGa0fcMQ=,tag:UUdDeVIja2L4hQNHb7yK2g==,type:str]
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:jLg06l7mUeFDBGU1jCmsE4DEN9F/cWdeo6iDyTAepMvgR2o+3ZE/04boSU2rdK6J3CnSk7TivmmZf5iYt5qA+NqynbSqOI0zK09Bh53VwxjXGeYSbb8/HqM98J4f2qt7m+onN0aZAJoCADLaKVIiybOyNyprjhkklQ==,iv:b/rLe8F/wSkj0l9ftFqenZrrd8+XyYzusy4YeuCw1fs=,tag:XSV0uv3jgHHxzXEuX4W8jQ==,type:str]
sops:
    age:
        - recipient: age1su7wslu0uwtef3uy6uzvvc4ke5lhk4un6tddaexqh2w8y5lvzu8qf29545
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZkJSWUYzeWtIeE1jVFFy
            MnJRSXlXY21LTGx3VlBoRm5mRGRZWmVqMENBCjFwRmtLN3ZYTW5Ia3BWcElvUUhZ
            VThLSUVLMGdSV2t4ZmFOaGhKcEJPOEEKLS0tIFkra09ndlJVRVo2QmF0WkZzUEdJ
            Rys0K3ByUWlJb0lBODU2MTJSNWRNd1EKQD4DgKgSTK6TNiMdIA9Su2txSO3w+R5y
            UiY2rqhsxVLKCGwB3DalGzpFx6qpSs+MjcQQJ78H6nebkYp+BP7vAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T04:39:45Z"
    mac: ENC[AES256_GCM,data:PZp657MGhu8t1ticM7UTqbu+yXZFGea1bPkqCPGXv+LMSjP0c8aV4qo2P3mcG/d+/9nmc0Bk8D0OATuNzCgLp34dcVhayUrCKmp+kqFOB6C7D1t4gWraYTk5RzkfiWRazIekeXVTZd/3HO5OOiUbkLjSGtoFo9zAT7WqjRjeThM=,iv:3Ph1YQqSbo3kYryjj7HcKckP61YtxP8KM/JYVYaMlQE=,tag:+hHW6KqUCym72wCt3XtSEA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
