apiVersion: ENC[AES256_GCM,data:878=,iv:5lvJA+yKPbif1+0Gm9oVLoGxctIONMqAlLTxVDourkI=,tag:dhXNwOTih8G7Sslc8PovSg==,type:str]
kind: ENC[AES256_GCM,data:yeIyrU9t,iv:wJKUcwviPKcr1zwy0NYjxsKUoJlc2VlgiS3pv4f3vKM=,tag:xpNNIWrDZZGlBoFVeBA+9g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:AxLp5EyDoySnOKjYGG4+tw==,iv:c+kOQfMzndfTTkrppHqL5kCUVv5RQVpnzEUIf2L37dc=,tag:apwzMLusLAEnJpxJ2hGN8w==,type:str]
type: ENC[AES256_GCM,data:eRn5v1Ox,iv:JTw/GkCWP0/WUf6nV1RP0r0AIz7QmeNm0LRenhPYV+E=,tag:7xlI4xKJ2Pu0hduBIwN9SQ==,type:str]
stringData:
    PROD_DB_URL: ENC[AES256_GCM,data:u4+0QTBtyZB94xT8gjiwT1Bex2UZye0i83Jo58Alvb/5EEuP/xwvhyboNVC7ChKxdOHYXd0t9hfwBcUb0h8VatZ5hMK91/nyWQ==,iv:/VXpIIyo4m5dfIWuoTrvYEH/QeysLKD5g9NsyI8CAZ4=,tag:K8mry3PEltkjIRFG0ijXaw==,type:str]
    PROD_DB_USERNAME: ENC[AES256_GCM,data:bkH3qog=,iv:IWw0BVmBPg9yOVde8gSCnT/pyqw/vi0dwqHbjNy0TFM=,tag:iLNAR5ll4aNJC/i2BiwJPg==,type:str]
    PROD_DB_PASSWORD: ENC[AES256_GCM,data:qrnreSSZ9F2e4dzysOmmzDQ9cG1pcYdHz7pOnCtw6Ac=,iv:HXH2jr/mXuI/Ys3qUPyCve2ztrntxLamhyWD//KMM9k=,tag:vRCNRAF35stlWVJyzVRc+Q==,type:str]
    PROD_JWT_SECRET: ENC[AES256_GCM,data:Dvyziidy5F8Deotgc++yy4uRhseTRR5yVGpN4DDp3IgEuHPaOPJEVH1ZJVapvxEid7jbE6nKHYH/aVzOXL9RWpf7U72SxcisCwenA8feikVmzSXAxOjXDw==,iv:o4wXNbsaom7BlENMvOJqQdNchV9n1FnnvSuNQHd5j0s=,tag:wnRnw6IxA4FEYMcfIIZHuQ==,type:str]
    MAIL_USERNAME: ENC[AES256_GCM,data:aDoi4BAeOt9FM4q0sZHfTQlGI97gjC0=,iv:3uJeqLTidTVgxns1ygZ7cBGu2B9cJ3WsLKV9aUYO6IU=,tag:uyBNDdrKhUHkgMqZnXHaZA==,type:str]
    MAIL_PASSWORD: ENC[AES256_GCM,data:M4QG9YXONuVLDkfJlBQGBAmvJg==,iv:1LSH/FWQooecHV2rZ2zOld4zkt7bwsEmGjA7mE9cirI=,tag:DjqGLyBq/II2HX9gqxnzuA==,type:str]
    KAKAO_KEY: ENC[AES256_GCM,data:zrf3aa4oXsw/FIbKjfqkv7gIthc9eM8a9AQZuVqAKd8=,iv:DjWWtAHd+ohrHnVA1neGPRlTX00eI3ZHPW7gUGPE+Rk=,tag:srvAgH/UI+TgPjXqPmD6Uw==,type:str]
    KAKAO_CLIENT_SECRET: ENC[AES256_GCM,data:i41KZkzNvfKr2Gtm+i9yVjN0f5vQ6JibufhBhfuAj+w=,iv:egqzBDsyWI9k0RzButAVuwLVIB4O8YJZmkLy1Fn1l6w=,tag:cMZZ3rxp8VaLnmRp1YIldQ==,type:str]
    GOOGLE_KEY: ENC[AES256_GCM,data:NKfbC+2pCqvXhWV+YdqnKyHwlHHVllstBnm11MfQ7Yqa6DPcLU93,iv:HhrcNX4gcO2lZJmKnNQ0rmnfc7n/XIz+b0SvvMzqdnU=,tag:nfeqYmPBvHQhjZfgdRVP8A==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:/FDKIMQsh7KeA4vuPFnK96ZgMJwm6+a1ss7ZFrb3M9glmi6xqvEj,iv:skj7bIIo2ZIgVUZ90+H6in9zqyM++/43zhGX6CbGx+4=,tag:CRXYyXpkB04wkWf0+V4qMQ==,type:str]
    EXCHANGE_RATE_API_KEY: ENC[AES256_GCM,data:rKtVamI47+JtAo2y104JBSwab17rNm4Fd9Qw7iiLhwI=,iv:XjgK4IZpHcgeh/ZuA/sik+hNkA2TfbLUu1jt6ys+j/w=,tag:g3ouTKn9ceVLIjaAcFDv7g==,type:str]
    CLOUDINARY_URL: ENC[AES256_GCM,data:m6X5O0jKZH6gRG0oOEqzsfg04d/jjFgRNm4PdFWcTtmSlFEOV+0tDtGHF014U1mMUyi+8mOxyHL6EemsfTguVUQL,iv:uwwAJqnSMV7CAebQgeR5npFFrLBQ+jJLWQnbZ6y9glc=,tag:RXGMb5YDCwb1goDj1QBNUQ==,type:str]
sops:
    age:
        - recipient: age1su7wslu0uwtef3uy6uzvvc4ke5lhk4un6tddaexqh2w8y5lvzu8qf29545
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZGlJQlozdTY5ZXdxdm04
            SkE2Yk9aVkNDR2JxWTl6WjhHem5GaEpuWjJRCmRZNGtHN1AvOHNCdFR5VlZoOUFX
            dldTQlJ0ZWFNK3Z6V1FPS0c3cVN0MWcKLS0tIFl1Ukl1a1FtVTN4cGFZc0NWNnhF
            bkxlcHNsRXFudDUwb1gxNWorZ0JFTXcKkFcmKTRafY4lOX+0VFUMO/iNbQx4UBE/
            LtVyirj84x8qAodI3HMdJHChkYNxfNIMhJ5reLzrzEIuz8IhPxhMaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T01:17:19Z"
    mac: ENC[AES256_GCM,data:5u7KSihuPJzIVbC1OXowVdfxT4urxZBXF/SBrNGRPYOcfSblsqHt2oBILgJiS9CbVjygZ2NkUr9ZwckAg/A/irZ166NUJWIDzNbtilpmbxm8eThRl4FNJlwlaz00hpqDmGorxVVlkZTRtT/wNdiNdxV4X9w3b1wTz1U2WVJzdCw=,iv:8nCNy7ge3XSKz1colRQfcDDeYjLsWlSJBf53zuvqjwE=,tag:qb3rLxfxnZOB941dbVQOXw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
