apiVersion: v1
kind: Secret
metadata:
  name: tribe-api-secret
type: Opaque
stringData:
  PROD_DB_URL: "jdbc:postgresql://shared-postgresql.database.svc.cluster.local:5432/tribe"
  PROD_DB_USERNAME: "postgres"
  PROD_DB_PASSWORD: "replace-me"
  PROD_JWT_SECRET: "replace-me"
  MAIL_USERNAME: "noreply@example.com"
  MAIL_PASSWORD: "replace-me"
  KAKAO_KEY: "replace-me"
  KAKAO_CLIENT_SECRET: "replace-me"
  GOOGLE_KEY: "replace-me"
  GEMINI_API_KEY: "replace-me"
  EXCHANGE_RATE_API_KEY: "replace-me"
  CLOUDINARY_URL: "replace-me"
