package com.tribe.domain.trip.core

enum class TripRegion(
    val code: String,
    val country: Country,
    val label: String,
    val type: TripRegionType,
    val centerLat: Double,
    val centerLng: Double,
    val searchHints: List<String>,
) {
    KR_SEOUL(
        code = "KR_SEOUL",
        country = Country.SOUTH_KOREA,
        label = "서울",
        type = TripRegionType.CITY,
        centerLat = 37.5665,
        centerLng = 126.9780,
        searchHints = listOf("서울", "Seoul"),
    ),
    KR_BUSAN(
        code = "KR_BUSAN",
        country = Country.SOUTH_KOREA,
        label = "부산",
        type = TripRegionType.CITY,
        centerLat = 35.1796,
        centerLng = 129.0756,
        searchHints = listOf("부산", "Busan"),
    ),
    KR_JEJU(
        code = "KR_JEJU",
        country = Country.SOUTH_KOREA,
        label = "제주",
        type = TripRegionType.ISLAND,
        centerLat = 33.4996,
        centerLng = 126.5312,
        searchHints = listOf("제주", "Jeju"),
    ),
    KR_GANGNEUNG_SOKCHO(
        code = "KR_GANGNEUNG_SOKCHO",
        country = Country.SOUTH_KOREA,
        label = "강릉/속초",
        type = TripRegionType.AREA,
        centerLat = 37.7519,
        centerLng = 128.8761,
        searchHints = listOf("강릉", "속초", "Gangneung", "Sokcho"),
    ),
    JP_TOKYO(
        code = "JP_TOKYO",
        country = Country.JAPAN,
        label = "도쿄",
        type = TripRegionType.CITY,
        centerLat = 35.6762,
        centerLng = 139.6503,
        searchHints = listOf("도쿄", "Tokyo"),
    ),
    JP_OSAKA_KYOTO(
        code = "JP_OSAKA_KYOTO",
        country = Country.JAPAN,
        label = "오사카/교토",
        type = TripRegionType.METRO,
        centerLat = 34.6937,
        centerLng = 135.5023,
        searchHints = listOf("오사카", "교토", "Osaka", "Kyoto"),
    ),
    JP_HOKKAIDO(
        code = "JP_HOKKAIDO",
        country = Country.JAPAN,
        label = "홋카이도",
        type = TripRegionType.AREA,
        centerLat = 43.0618,
        centerLng = 141.3545,
        searchHints = listOf("홋카이도", "삿포로", "Hokkaido", "Sapporo"),
    ),
    JP_OKINAWA(
        code = "JP_OKINAWA",
        country = Country.JAPAN,
        label = "오키나와",
        type = TripRegionType.ISLAND,
        centerLat = 26.2124,
        centerLng = 127.6809,
        searchHints = listOf("오키나와", "나하", "Okinawa", "Naha"),
    ),
    JP_FUKUOKA(
        code = "JP_FUKUOKA",
        country = Country.JAPAN,
        label = "후쿠오카",
        type = TripRegionType.CITY,
        centerLat = 33.5902,
        centerLng = 130.4017,
        searchHints = listOf("후쿠오카", "Fukuoka"),
    ),
    CN_BEIJING(
        code = "CN_BEIJING",
        country = Country.CHINA,
        label = "베이징",
        type = TripRegionType.CITY,
        centerLat = 39.9042,
        centerLng = 116.4074,
        searchHints = listOf("베이징", "북경", "Beijing"),
    ),
    CN_SHANGHAI(
        code = "CN_SHANGHAI",
        country = Country.CHINA,
        label = "상하이",
        type = TripRegionType.CITY,
        centerLat = 31.2304,
        centerLng = 121.4737,
        searchHints = listOf("상하이", "Shanghai"),
    ),
    CN_GUANGZHOU_SHENZHEN(
        code = "CN_GUANGZHOU_SHENZHEN",
        country = Country.CHINA,
        label = "광저우/선전",
        type = TripRegionType.METRO,
        centerLat = 23.1291,
        centerLng = 113.2644,
        searchHints = listOf("광저우", "선전", "Guangzhou", "Shenzhen"),
    ),
    CN_CHENGDU_XIAN(
        code = "CN_CHENGDU_XIAN",
        country = Country.CHINA,
        label = "청두/시안",
        type = TripRegionType.AREA,
        centerLat = 30.5728,
        centerLng = 104.0668,
        searchHints = listOf("청두", "시안", "Chengdu", "Xian"),
    ),
    TH_BANGKOK(
        code = "TH_BANGKOK",
        country = Country.THAILAND,
        label = "방콕",
        type = TripRegionType.CITY,
        centerLat = 13.7563,
        centerLng = 100.5018,
        searchHints = listOf("방콕", "Bangkok"),
    ),
    TH_CHIANG_MAI(
        code = "TH_CHIANG_MAI",
        country = Country.THAILAND,
        label = "치앙마이",
        type = TripRegionType.CITY,
        centerLat = 18.7883,
        centerLng = 98.9853,
        searchHints = listOf("치앙마이", "Chiang Mai"),
    ),
    TH_PHUKET_KRABI(
        code = "TH_PHUKET_KRABI",
        country = Country.THAILAND,
        label = "푸켓/끄라비",
        type = TripRegionType.AREA,
        centerLat = 7.8804,
        centerLng = 98.3923,
        searchHints = listOf("푸켓", "끄라비", "Phuket", "Krabi"),
    ),
    VN_HANOI(
        code = "VN_HANOI",
        country = Country.VIETNAM,
        label = "하노이",
        type = TripRegionType.CITY,
        centerLat = 21.0278,
        centerLng = 105.8342,
        searchHints = listOf("하노이", "Hanoi"),
    ),
    VN_DA_NANG_HOI_AN(
        code = "VN_DA_NANG_HOI_AN",
        country = Country.VIETNAM,
        label = "다낭/호이안",
        type = TripRegionType.AREA,
        centerLat = 16.0544,
        centerLng = 108.2022,
        searchHints = listOf("다낭", "호이안", "Da Nang", "Hoi An"),
    ),
    VN_HO_CHI_MINH(
        code = "VN_HO_CHI_MINH",
        country = Country.VIETNAM,
        label = "호치민",
        type = TripRegionType.CITY,
        centerLat = 10.8231,
        centerLng = 106.6297,
        searchHints = listOf("호치민", "Ho Chi Minh", "Saigon"),
    ),
    PH_MANILA(
        code = "PH_MANILA",
        country = Country.PHILIPPINES,
        label = "마닐라",
        type = TripRegionType.CITY,
        centerLat = 14.5995,
        centerLng = 120.9842,
        searchHints = listOf("마닐라", "Manila"),
    ),
    PH_CEBU_BOHOL(
        code = "PH_CEBU_BOHOL",
        country = Country.PHILIPPINES,
        label = "세부/보홀",
        type = TripRegionType.AREA,
        centerLat = 10.3157,
        centerLng = 123.8854,
        searchHints = listOf("세부", "보홀", "Cebu", "Bohol"),
    ),
    PH_PALAWAN_BORACAY(
        code = "PH_PALAWAN_BORACAY",
        country = Country.PHILIPPINES,
        label = "팔라완/보라카이",
        type = TripRegionType.AREA,
        centerLat = 11.9674,
        centerLng = 121.9248,
        searchHints = listOf("팔라완", "보라카이", "Palawan", "Boracay"),
    ),
    SG_SINGAPORE(
        code = "SG_SINGAPORE",
        country = Country.SINGAPORE,
        label = "싱가포르 시티",
        type = TripRegionType.CITY,
        centerLat = 1.3521,
        centerLng = 103.8198,
        searchHints = listOf("싱가포르", "Singapore"),
    ),
    MY_KUALA_LUMPUR(
        code = "MY_KUALA_LUMPUR",
        country = Country.MALAYSIA,
        label = "쿠알라룸푸르",
        type = TripRegionType.CITY,
        centerLat = 3.1390,
        centerLng = 101.6869,
        searchHints = listOf("쿠알라룸푸르", "Kuala Lumpur"),
    ),
    MY_PENANG(
        code = "MY_PENANG",
        country = Country.MALAYSIA,
        label = "페낭",
        type = TripRegionType.AREA,
        centerLat = 5.4141,
        centerLng = 100.3288,
        searchHints = listOf("페낭", "Penang"),
    ),
    MY_KOTA_KINABALU(
        code = "MY_KOTA_KINABALU",
        country = Country.MALAYSIA,
        label = "코타키나발루",
        type = TripRegionType.CITY,
        centerLat = 5.9804,
        centerLng = 116.0735,
        searchHints = listOf("코타키나발루", "Kota Kinabalu"),
    ),
    ID_JAKARTA(
        code = "ID_JAKARTA",
        country = Country.INDONESIA,
        label = "자카르타",
        type = TripRegionType.CITY,
        centerLat = -6.2088,
        centerLng = 106.8456,
        searchHints = listOf("자카르타", "Jakarta"),
    ),
    ID_BALI(
        code = "ID_BALI",
        country = Country.INDONESIA,
        label = "발리",
        type = TripRegionType.ISLAND,
        centerLat = -8.3405,
        centerLng = 115.0920,
        searchHints = listOf("발리", "Bali"),
    ),
    ID_YOGYAKARTA(
        code = "ID_YOGYAKARTA",
        country = Country.INDONESIA,
        label = "족자카르타",
        type = TripRegionType.CITY,
        centerLat = -7.7956,
        centerLng = 110.3695,
        searchHints = listOf("족자카르타", "Yogyakarta"),
    ),
    IN_DELHI_AGRA(
        code = "IN_DELHI_AGRA",
        country = Country.INDIA,
        label = "델리/아그라",
        type = TripRegionType.AREA,
        centerLat = 28.6139,
        centerLng = 77.2090,
        searchHints = listOf("델리", "아그라", "Delhi", "Agra"),
    ),
    IN_MUMBAI(
        code = "IN_MUMBAI",
        country = Country.INDIA,
        label = "뭄바이",
        type = TripRegionType.CITY,
        centerLat = 19.0760,
        centerLng = 72.8777,
        searchHints = listOf("뭄바이", "Mumbai"),
    ),
    IN_GOA(
        code = "IN_GOA",
        country = Country.INDIA,
        label = "고아",
        type = TripRegionType.AREA,
        centerLat = 15.2993,
        centerLng = 74.1240,
        searchHints = listOf("고아", "Goa"),
    ),
    IN_JAIPUR_UDAIPUR(
        code = "IN_JAIPUR_UDAIPUR",
        country = Country.INDIA,
        label = "자이푸르/우다이푸르",
        type = TripRegionType.AREA,
        centerLat = 26.9124,
        centerLng = 75.7873,
        searchHints = listOf("자이푸르", "우다이푸르", "Jaipur", "Udaipur"),
    ),
    AE_DUBAI(
        code = "AE_DUBAI",
        country = Country.UAE,
        label = "두바이",
        type = TripRegionType.CITY,
        centerLat = 25.2048,
        centerLng = 55.2708,
        searchHints = listOf("두바이", "Dubai"),
    ),
    AE_ABU_DHABI(
        code = "AE_ABU_DHABI",
        country = Country.UAE,
        label = "아부다비",
        type = TripRegionType.CITY,
        centerLat = 24.4539,
        centerLng = 54.3773,
        searchHints = listOf("아부다비", "Abu Dhabi"),
    ),
    AE_SHARJAH_NORTHERN(
        code = "AE_SHARJAH_NORTHERN",
        country = Country.UAE,
        label = "샤르자/북부 에미리트",
        type = TripRegionType.AREA,
        centerLat = 25.3463,
        centerLng = 55.4209,
        searchHints = listOf("샤르자", "Sharjah"),
    ),
    TR_ISTANBUL(
        code = "TR_ISTANBUL",
        country = Country.TURKEY,
        label = "이스탄불",
        type = TripRegionType.CITY,
        centerLat = 41.0082,
        centerLng = 28.9784,
        searchHints = listOf("이스탄불", "Istanbul"),
    ),
    TR_CAPPADOCIA(
        code = "TR_CAPPADOCIA",
        country = Country.TURKEY,
        label = "카파도키아",
        type = TripRegionType.AREA,
        centerLat = 38.6431,
        centerLng = 34.8270,
        searchHints = listOf("카파도키아", "Cappadocia"),
    ),
    TR_ANTALYA_IZMIR(
        code = "TR_ANTALYA_IZMIR",
        country = Country.TURKEY,
        label = "안탈리아/이즈미르",
        type = TripRegionType.AREA,
        centerLat = 36.8969,
        centerLng = 30.7133,
        searchHints = listOf("안탈리아", "이즈미르", "Antalya", "Izmir"),
    ),
    EG_CAIRO_GIZA(
        code = "EG_CAIRO_GIZA",
        country = Country.EGYPT,
        label = "카이로/기자",
        type = TripRegionType.AREA,
        centerLat = 30.0444,
        centerLng = 31.2357,
        searchHints = listOf("카이로", "기자", "Cairo", "Giza"),
    ),
    EG_LUXOR_ASWAN(
        code = "EG_LUXOR_ASWAN",
        country = Country.EGYPT,
        label = "룩소르/아스완",
        type = TripRegionType.AREA,
        centerLat = 25.6872,
        centerLng = 32.6396,
        searchHints = listOf("룩소르", "아스완", "Luxor", "Aswan"),
    ),
    EG_SHARM_EL_SHEIKH(
        code = "EG_SHARM_EL_SHEIKH",
        country = Country.EGYPT,
        label = "샤름엘셰이크",
        type = TripRegionType.CITY,
        centerLat = 27.9158,
        centerLng = 34.3300,
        searchHints = listOf("샤름엘셰이크", "Sharm El Sheikh"),
    ),
    IT_ROME(
        code = "IT_ROME",
        country = Country.ITALY,
        label = "로마",
        type = TripRegionType.CITY,
        centerLat = 41.9028,
        centerLng = 12.4964,
        searchHints = listOf("로마", "Rome"),
    ),
    IT_MILAN_LAKE_COMO(
        code = "IT_MILAN_LAKE_COMO",
        country = Country.ITALY,
        label = "밀라노/코모호",
        type = TripRegionType.AREA,
        centerLat = 45.4642,
        centerLng = 9.1900,
        searchHints = listOf("밀라노", "코모", "Milan", "Como"),
    ),
    IT_VENICE_FLORENCE(
        code = "IT_VENICE_FLORENCE",
        country = Country.ITALY,
        label = "베네치아/피렌체",
        type = TripRegionType.AREA,
        centerLat = 43.7696,
        centerLng = 11.2558,
        searchHints = listOf("베네치아", "피렌체", "Venice", "Florence"),
    ),
    IT_NAPLES_AMALFI(
        code = "IT_NAPLES_AMALFI",
        country = Country.ITALY,
        label = "나폴리/아말피",
        type = TripRegionType.AREA,
        centerLat = 40.8518,
        centerLng = 14.2681,
        searchHints = listOf("나폴리", "아말피", "Naples", "Amalfi"),
    ),
    FR_PARIS(
        code = "FR_PARIS",
        country = Country.FRANCE,
        label = "파리",
        type = TripRegionType.CITY,
        centerLat = 48.8566,
        centerLng = 2.3522,
        searchHints = listOf("파리", "Paris"),
    ),
    FR_NICE_PROVENCE(
        code = "FR_NICE_PROVENCE",
        country = Country.FRANCE,
        label = "니스/프로방스",
        type = TripRegionType.AREA,
        centerLat = 43.7102,
        centerLng = 7.2620,
        searchHints = listOf("니스", "프로방스", "Nice", "Provence"),
    ),
    FR_LYON_ALPS(
        code = "FR_LYON_ALPS",
        country = Country.FRANCE,
        label = "리옹/알프스",
        type = TripRegionType.AREA,
        centerLat = 45.7640,
        centerLng = 4.8357,
        searchHints = listOf("리옹", "알프스", "Lyon", "Alps"),
    ),
    ES_MADRID(
        code = "ES_MADRID",
        country = Country.SPAIN,
        label = "마드리드",
        type = TripRegionType.CITY,
        centerLat = 40.4168,
        centerLng = -3.7038,
        searchHints = listOf("마드리드", "Madrid"),
    ),
    ES_BARCELONA(
        code = "ES_BARCELONA",
        country = Country.SPAIN,
        label = "바르셀로나",
        type = TripRegionType.CITY,
        centerLat = 41.3874,
        centerLng = 2.1686,
        searchHints = listOf("바르셀로나", "Barcelona"),
    ),
    ES_ANDALUSIA(
        code = "ES_ANDALUSIA",
        country = Country.SPAIN,
        label = "안달루시아",
        type = TripRegionType.AREA,
        centerLat = 37.3891,
        centerLng = -5.9845,
        searchHints = listOf("세비야", "그라나다", "말라가", "Andalusia"),
    ),
    ES_MALLORCA_IBIZA(
        code = "ES_MALLORCA_IBIZA",
        country = Country.SPAIN,
        label = "마요르카/이비사",
        type = TripRegionType.ISLAND,
        centerLat = 39.5696,
        centerLng = 2.6502,
        searchHints = listOf("마요르카", "이비사", "Mallorca", "Ibiza"),
    ),
    GB_LONDON(
        code = "GB_LONDON",
        country = Country.UK,
        label = "런던",
        type = TripRegionType.CITY,
        centerLat = 51.5074,
        centerLng = -0.1278,
        searchHints = listOf("런던", "London"),
    ),
    GB_EDINBURGH_HIGHLANDS(
        code = "GB_EDINBURGH_HIGHLANDS",
        country = Country.UK,
        label = "에든버러/하이랜드",
        type = TripRegionType.AREA,
        centerLat = 55.9533,
        centerLng = -3.1883,
        searchHints = listOf("에든버러", "하이랜드", "Edinburgh", "Highlands"),
    ),
    GB_MANCHESTER_LIVERPOOL(
        code = "GB_MANCHESTER_LIVERPOOL",
        country = Country.UK,
        label = "맨체스터/리버풀",
        type = TripRegionType.AREA,
        centerLat = 53.4808,
        centerLng = -2.2426,
        searchHints = listOf("맨체스터", "리버풀", "Manchester", "Liverpool"),
    ),
    DE_BERLIN(
        code = "DE_BERLIN",
        country = Country.GERMANY,
        label = "베를린",
        type = TripRegionType.CITY,
        centerLat = 52.5200,
        centerLng = 13.4050,
        searchHints = listOf("베를린", "Berlin"),
    ),
    DE_MUNICH_BAVARIA(
        code = "DE_MUNICH_BAVARIA",
        country = Country.GERMANY,
        label = "뮌헨/바이에른",
        type = TripRegionType.AREA,
        centerLat = 48.1351,
        centerLng = 11.5820,
        searchHints = listOf("뮌헨", "바이에른", "Munich", "Bavaria"),
    ),
    DE_FRANKFURT_RHINE(
        code = "DE_FRANKFURT_RHINE",
        country = Country.GERMANY,
        label = "프랑크푸르트/라인",
        type = TripRegionType.AREA,
        centerLat = 50.1109,
        centerLng = 8.6821,
        searchHints = listOf("프랑크푸르트", "라인", "Frankfurt", "Rhine"),
    ),
    CH_ZURICH_LUCERNE(
        code = "CH_ZURICH_LUCERNE",
        country = Country.SWITZERLAND,
        label = "취리히/루체른",
        type = TripRegionType.AREA,
        centerLat = 47.3769,
        centerLng = 8.5417,
        searchHints = listOf("취리히", "루체른", "Zurich", "Lucerne"),
    ),
    CH_INTERLAKEN_BERNESE(
        code = "CH_INTERLAKEN_BERNESE",
        country = Country.SWITZERLAND,
        label = "인터라켄/베르너오버란트",
        type = TripRegionType.AREA,
        centerLat = 46.6863,
        centerLng = 7.8632,
        searchHints = listOf("인터라켄", "융프라우", "Interlaken", "Bernese Oberland"),
    ),
    CH_GENEVA_MONTREUX(
        code = "CH_GENEVA_MONTREUX",
        country = Country.SWITZERLAND,
        label = "제네바/몽트뢰",
        type = TripRegionType.AREA,
        centerLat = 46.2044,
        centerLng = 6.1432,
        searchHints = listOf("제네바", "몽트뢰", "Geneva", "Montreux"),
    ),
    NL_AMSTERDAM(
        code = "NL_AMSTERDAM",
        country = Country.NETHERLANDS,
        label = "암스테르담",
        type = TripRegionType.CITY,
        centerLat = 52.3676,
        centerLng = 4.9041,
        searchHints = listOf("암스테르담", "Amsterdam"),
    ),
    NL_ROTTERDAM_THE_HAGUE(
        code = "NL_ROTTERDAM_THE_HAGUE",
        country = Country.NETHERLANDS,
        label = "로테르담/헤이그",
        type = TripRegionType.AREA,
        centerLat = 51.9244,
        centerLng = 4.4777,
        searchHints = listOf("로테르담", "헤이그", "Rotterdam", "The Hague"),
    ),
    NL_UTRECHT_GIETHOORN(
        code = "NL_UTRECHT_GIETHOORN",
        country = Country.NETHERLANDS,
        label = "위트레흐트/히트호른",
        type = TripRegionType.AREA,
        centerLat = 52.0907,
        centerLng = 5.1214,
        searchHints = listOf("위트레흐트", "히트호른", "Utrecht", "Giethoorn"),
    ),
    GR_ATHENS(
        code = "GR_ATHENS",
        country = Country.GREECE,
        label = "아테네",
        type = TripRegionType.CITY,
        centerLat = 37.9838,
        centerLng = 23.7275,
        searchHints = listOf("아테네", "Athens"),
    ),
    GR_SANTORINI_CYCLADES(
        code = "GR_SANTORINI_CYCLADES",
        country = Country.GREECE,
        label = "산토리니/키클라데스",
        type = TripRegionType.ISLAND,
        centerLat = 36.3932,
        centerLng = 25.4615,
        searchHints = listOf("산토리니", "미코노스", "Santorini", "Cyclades"),
    ),
    GR_CRETE(
        code = "GR_CRETE",
        country = Country.GREECE,
        label = "크레타",
        type = TripRegionType.ISLAND,
        centerLat = 35.2401,
        centerLng = 24.8093,
        searchHints = listOf("크레타", "Crete"),
    ),
    US_NEW_YORK(
        code = "US_NEW_YORK",
        country = Country.USA,
        label = "뉴욕",
        type = TripRegionType.CITY,
        centerLat = 40.7128,
        centerLng = -74.0060,
        searchHints = listOf("뉴욕", "New York"),
    ),
    US_CALIFORNIA_WEST(
        code = "US_CALIFORNIA_WEST",
        country = Country.USA,
        label = "캘리포니아 서부",
        type = TripRegionType.AREA,
        centerLat = 34.0522,
        centerLng = -118.2437,
        searchHints = listOf("로스앤젤레스", "샌프란시스코", "California", "Los Angeles", "San Francisco"),
    ),
    US_HAWAII(
        code = "US_HAWAII",
        country = Country.USA,
        label = "하와이",
        type = TripRegionType.ISLAND,
        centerLat = 21.3069,
        centerLng = -157.8583,
        searchHints = listOf("하와이", "호놀룰루", "Hawaii", "Honolulu"),
    ),
    US_FLORIDA(
        code = "US_FLORIDA",
        country = Country.USA,
        label = "플로리다",
        type = TripRegionType.AREA,
        centerLat = 25.7617,
        centerLng = -80.1918,
        searchHints = listOf("마이애미", "올랜도", "Florida", "Miami", "Orlando"),
    ),
    CA_TORONTO(
        code = "CA_TORONTO",
        country = Country.CANADA,
        label = "토론토",
        type = TripRegionType.CITY,
        centerLat = 43.6532,
        centerLng = -79.3832,
        searchHints = listOf("토론토", "Toronto"),
    ),
    CA_VANCOUVER(
        code = "CA_VANCOUVER",
        country = Country.CANADA,
        label = "밴쿠버",
        type = TripRegionType.CITY,
        centerLat = 49.2827,
        centerLng = -123.1207,
        searchHints = listOf("밴쿠버", "Vancouver"),
    ),
    CA_BANFF_JASPER(
        code = "CA_BANFF_JASPER",
        country = Country.CANADA,
        label = "밴프/재스퍼",
        type = TripRegionType.AREA,
        centerLat = 51.1784,
        centerLng = -115.5708,
        searchHints = listOf("밴프", "재스퍼", "Banff", "Jasper"),
    ),
    CA_MONTREAL_QUEBEC(
        code = "CA_MONTREAL_QUEBEC",
        country = Country.CANADA,
        label = "몬트리올/퀘벡시티",
        type = TripRegionType.AREA,
        centerLat = 45.5017,
        centerLng = -73.5673,
        searchHints = listOf("몬트리올", "퀘벡", "Montreal", "Quebec City"),
    ),
    AU_SYDNEY(
        code = "AU_SYDNEY",
        country = Country.AUSTRALIA,
        label = "시드니",
        type = TripRegionType.CITY,
        centerLat = -33.8688,
        centerLng = 151.2093,
        searchHints = listOf("시드니", "Sydney"),
    ),
    AU_MELBOURNE_GREAT_OCEAN(
        code = "AU_MELBOURNE_GREAT_OCEAN",
        country = Country.AUSTRALIA,
        label = "멜버른/그레이트오션로드",
        type = TripRegionType.AREA,
        centerLat = -37.8136,
        centerLng = 144.9631,
        searchHints = listOf("멜버른", "그레이트오션로드", "Melbourne", "Great Ocean Road"),
    ),
    AU_GOLD_COAST_CAIRNS(
        code = "AU_GOLD_COAST_CAIRNS",
        country = Country.AUSTRALIA,
        label = "골드코스트/케언스",
        type = TripRegionType.AREA,
        centerLat = -28.0167,
        centerLng = 153.4000,
        searchHints = listOf("골드코스트", "케언스", "Gold Coast", "Cairns"),
    ),
    AU_PERTH(
        code = "AU_PERTH",
        country = Country.AUSTRALIA,
        label = "퍼스",
        type = TripRegionType.CITY,
        centerLat = -31.9505,
        centerLng = 115.8605,
        searchHints = listOf("퍼스", "Perth"),
    ),
    NZ_AUCKLAND(
        code = "NZ_AUCKLAND",
        country = Country.NEW_ZEALAND,
        label = "오클랜드",
        type = TripRegionType.CITY,
        centerLat = -36.8509,
        centerLng = 174.7645,
        searchHints = listOf("오클랜드", "Auckland"),
    ),
    NZ_QUEENSTOWN(
        code = "NZ_QUEENSTOWN",
        country = Country.NEW_ZEALAND,
        label = "퀸스타운",
        type = TripRegionType.CITY,
        centerLat = -45.0312,
        centerLng = 168.6626,
        searchHints = listOf("퀸스타운", "Queenstown"),
    ),
    NZ_CHRISTCHURCH_TEKAPO(
        code = "NZ_CHRISTCHURCH_TEKAPO",
        country = Country.NEW_ZEALAND,
        label = "크라이스트처치/테카포",
        type = TripRegionType.AREA,
        centerLat = -43.5321,
        centerLng = 172.6362,
        searchHints = listOf("크라이스트처치", "테카포", "Christchurch", "Tekapo"),
    ),
    BR_RIO_DE_JANEIRO(
        code = "BR_RIO_DE_JANEIRO",
        country = Country.BRAZIL,
        label = "리우데자네이루",
        type = TripRegionType.CITY,
        centerLat = -22.9068,
        centerLng = -43.1729,
        searchHints = listOf("리우데자네이루", "Rio de Janeiro"),
    ),
    BR_SAO_PAULO(
        code = "BR_SAO_PAULO",
        country = Country.BRAZIL,
        label = "상파울루",
        type = TripRegionType.CITY,
        centerLat = -23.5505,
        centerLng = -46.6333,
        searchHints = listOf("상파울루", "Sao Paulo"),
    ),
    BR_SALVADOR(
        code = "BR_SALVADOR",
        country = Country.BRAZIL,
        label = "살바도르",
        type = TripRegionType.CITY,
        centerLat = -12.9777,
        centerLng = -38.5016,
        searchHints = listOf("살바도르", "Salvador"),
    ),
    BR_IGUAZU(
        code = "BR_IGUAZU",
        country = Country.BRAZIL,
        label = "이구아수",
        type = TripRegionType.AREA,
        centerLat = -25.6953,
        centerLng = -54.4367,
        searchHints = listOf("이구아수", "Foz do Iguacu", "Iguazu"),
    ),
    AR_BUENOS_AIRES(
        code = "AR_BUENOS_AIRES",
        country = Country.ARGENTINA,
        label = "부에노스아이레스",
        type = TripRegionType.CITY,
        centerLat = -34.6037,
        centerLng = -58.3816,
        searchHints = listOf("부에노스아이레스", "Buenos Aires"),
    ),
    AR_PATAGONIA(
        code = "AR_PATAGONIA",
        country = Country.ARGENTINA,
        label = "파타고니아",
        type = TripRegionType.AREA,
        centerLat = -50.3379,
        centerLng = -72.2648,
        searchHints = listOf("파타고니아", "엘칼라파테", "Patagonia", "El Calafate"),
    ),
    AR_MENDOZA(
        code = "AR_MENDOZA",
        country = Country.ARGENTINA,
        label = "멘도사",
        type = TripRegionType.CITY,
        centerLat = -32.8895,
        centerLng = -68.8458,
        searchHints = listOf("멘도사", "Mendoza"),
    ),
    AR_IGUAZU(
        code = "AR_IGUAZU",
        country = Country.ARGENTINA,
        label = "이과수",
        type = TripRegionType.AREA,
        centerLat = -25.5972,
        centerLng = -54.5786,
        searchHints = listOf("이과수", "Iguazu"),
    ),
    MX_MEXICO_CITY(
        code = "MX_MEXICO_CITY",
        country = Country.MEXICO,
        label = "멕시코시티",
        type = TripRegionType.CITY,
        centerLat = 19.4326,
        centerLng = -99.1332,
        searchHints = listOf("멕시코시티", "Mexico City"),
    ),
    MX_CANCUN_RIVIERA_MAYA(
        code = "MX_CANCUN_RIVIERA_MAYA",
        country = Country.MEXICO,
        label = "칸쿤/리비에라 마야",
        type = TripRegionType.AREA,
        centerLat = 21.1619,
        centerLng = -86.8515,
        searchHints = listOf("칸쿤", "리비에라 마야", "Cancun", "Riviera Maya"),
    ),
    MX_GUADALAJARA_PUERTO_VALLARTA(
        code = "MX_GUADALAJARA_PUERTO_VALLARTA",
        country = Country.MEXICO,
        label = "과달라하라/푸에르토바야르타",
        type = TripRegionType.AREA,
        centerLat = 20.6597,
        centerLng = -103.3496,
        searchHints = listOf("과달라하라", "푸에르토바야르타", "Guadalajara", "Puerto Vallarta"),
    ),
    ZA_CAPE_TOWN(
        code = "ZA_CAPE_TOWN",
        country = Country.SOUTH_AFRICA,
        label = "케이프타운",
        type = TripRegionType.CITY,
        centerLat = -33.9249,
        centerLng = 18.4241,
        searchHints = listOf("케이프타운", "Cape Town"),
    ),
    ZA_JOHANNESBURG(
        code = "ZA_JOHANNESBURG",
        country = Country.SOUTH_AFRICA,
        label = "요하네스버그",
        type = TripRegionType.CITY,
        centerLat = -26.2041,
        centerLng = 28.0473,
        searchHints = listOf("요하네스버그", "Johannesburg"),
    ),
    ZA_GARDEN_ROUTE_DURBAN(
        code = "ZA_GARDEN_ROUTE_DURBAN",
        country = Country.SOUTH_AFRICA,
        label = "가든루트/더반",
        type = TripRegionType.AREA,
        centerLat = -29.8587,
        centerLng = 31.0218,
        searchHints = listOf("가든루트", "더반", "Garden Route", "Durban"),
    ),
    MA_MARRAKECH(
        code = "MA_MARRAKECH",
        country = Country.MOROCCO,
        label = "마라케시",
        type = TripRegionType.CITY,
        centerLat = 31.6295,
        centerLng = -7.9811,
        searchHints = listOf("마라케시", "Marrakech"),
    ),
    MA_CASABLANCA_RABAT(
        code = "MA_CASABLANCA_RABAT",
        country = Country.MOROCCO,
        label = "카사블랑카/라바트",
        type = TripRegionType.AREA,
        centerLat = 33.5731,
        centerLng = -7.5898,
        searchHints = listOf("카사블랑카", "라바트", "Casablanca", "Rabat"),
    ),
    MA_FES_CHEFCHAOUEN(
        code = "MA_FES_CHEFCHAOUEN",
        country = Country.MOROCCO,
        label = "페스/셰프샤우엔",
        type = TripRegionType.AREA,
        centerLat = 34.0181,
        centerLng = -5.0078,
        searchHints = listOf("페스", "셰프샤우엔", "Fes", "Chefchaouen"),
    ),
    ;

    companion object {
        fun from(code: String?): TripRegion? {
            if (code.isNullOrBlank()) {
                return null
            }
            return entries.firstOrNull { it.code.equals(code, ignoreCase = true) }
        }

        fun forCountry(country: Country): List<TripRegion> =
            entries.filter { it.country == country }
    }
}
