name: Deploy Tribe FE

on:
  push:
    branches: [ "release" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Rsync frontend to server
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/${{ secrets.SERVER_USER }}/apps/tribe//frontend/

      - name: Build and restart containers
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd /home/${{ secrets.SERVER_USER }}/apps/tribe/frontend
            docker-compose down
            docker-compose build
            docker-compose up -d
          EOF
